workerPoolSpecs:
  machineSpec:
    machineType: n1-highmem-2
    acceleratorType: NVIDIA_TESLA_T4
    acceleratorCount: 1
  replicaCount: 1
  diskSpec:
    bootDiskType: pd-standard
    bootDiskSizeGb: 100
  containerSpec:
    imageUri: <uri of GCP artifact repository>:<tag> #you can replace it whatever you want
    command: ["python3", "src/train.py"]
